/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hameed
 */
import java.io.BufferedReader;
 import javax.swing.JFileChooser;
 import java.io.File;  
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JTextField;
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Browse File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Scanner");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            JFrame parentFrame = new JFrame();
 
JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Specify a file to save");   
 
int userSelection = fileChooser.showSaveDialog(parentFrame);
 
if (userSelection == JFileChooser.APPROVE_OPTION) {
    File fileToSave = fileChooser.getSelectedFile();
    System.out.println("Save as file: " + fileToSave.getAbsolutePath());
    jTextField1.setText(fileToSave.getName());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
                                              
            FileReader fin = null;
            try {
                fin = new FileReader(jTextField1.getText());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
             String line = null;
            BufferedReader br= new BufferedReader(fin);
                 Scanner inFile = new Scanner( fin );
                  
 int caret=jTextArea1.getCaretPosition();
            
         
            
            try {
                while ((line = br.readLine()) != null) {
                    String delimater=" ";
                    String str="jkhsjkdh shdahs hkdh h sadj";
                    StringTokenizer st = new StringTokenizer(str, delimater, true);
                    int i=1;
                    while(st.hasMoreTokens()){
                        String token=st.nextToken();
                        System.out.println("String"+i+":"+token);
                        ++i;
                        
                        
                        
                        while(st.hasMoreTokens()){
                            jTextArea1.insert(st.nextToken(), caret);
                            
                            
                            
                            switch(st.nextToken()){
                                case "++":
                                    jTextArea1.insert("++"+" "+":Unary Operator "+"\n",caret);
                                    break;
                                case "--":
                                    jTextArea1.insert("--"+" "+":Unary Operator "+"\n",caret);
                                    break;
                                case "!":
                                    jTextArea1.insert("!"+" "+":Unary Operator "+"\n",caret);
                                    break;
                                case "+":
                                    jTextArea1.insert("+"+" "+":Airthmatic Operator "+"\n",caret);
                                    break;
                                case "-":
                                    jTextArea1.insert("-"+" "+":Airthmatic Operator "+"\n",caret);
                                    break;
                                case "*":
                                    jTextArea1.insert("*"+" "+":Airthmatic Operator "+"\n",caret);
                                    break;
                                case "/":
                                    jTextArea1.insert("/"+" "+":Airthmatic Operator "+"\n",caret);
                                    break;
                                case "%":
                                    jTextArea1.insert("%"+" "+":Airthmatic Operator "+"\n",caret);
                                    break;
                                case "<<":
                                    jTextArea1.insert("<<"+" "+":Rational Operator "+"\n",caret);
                                    break;
                                case ">>":
                                    jTextArea1.insert(">>"+" "+":Rational Operator "+"\n",caret);
                                    break;
                                    
                                case "=":
                                    jTextArea1.insert("="+" "+":Rational Operator "+"\n",caret);
                                    break;
                                case "(":
                                    jTextArea1.insert("("+" "+":Symbol "+"\n",caret);
                                    break;
                                case "&":
                                    jTextArea1.insert("&"+" "+":Conditional Operator "+"\n",caret);
                                    break;
                                case "|":
                                    jTextArea1.insert("|"+" "+":Conditional Operator "+"\n",caret);
                                    break;
                                case ")":
                                    jTextArea1.insert(")"+" "+":Symbol "+"\n",caret);
                                    break;
                                case "{":
                                    jTextArea1.insert("{"+" "+":Symbol "+"\n",caret);
                                    break;
                                case "}":
                                    jTextArea1.insert("}"+" "+":Symbol "+"\n",caret);
                                    break;
                                case "[":
                                    jTextArea1.insert("["+" "+":Symbol "+"\n",caret);
                                    break;
                                case "]":
                                    jTextArea1.insert("]"+" "+":Symbol "+"\n",caret);
                                    break;
                                case ".":
                                    jTextArea1.insert("."+" "+":Symbol "+"\n",caret);
                                    break;
                                case ",":
                                    jTextArea1.insert(","+" "+":Symbol "+"\n",caret);
                                    break;
                                case ";":
                                    jTextArea1.insert(";"+" "+":Symbol "+"\n",caret);
                                    break;
                                case ":":
                                    jTextArea1.insert(":"+" "+":Symbol "+"\n",caret);
                                    break;
                                case "'":
                                    jTextArea1.insert("'"+" "+":Symbol "+"\n",caret);
                                    break;
                                    
                                    
                                default:
                                    
                                    
                                    break;
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                            }
                        }
                  
                        
                        
                        
                        
                        
                    }
                }   } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
